"""
Patient summary reports.

Combines what the app already records -- observed vitals, the AI risk level and
recommendation, clinician follow-up, and open alerts -- into one downloadable
document. Gemini writes the narrative paragraph; everything else is assembled
deterministically from the database so the clinical facts in the report are never
model-generated.
"""
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

# pyrefly: ignore [missing-import]
import httpx
# pyrefly: ignore [missing-import]
from sqlalchemy import select, desc
# pyrefly: ignore [missing-import]
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logging import logger
from app.database.models import (
    Patient, SensorReading, AIPrediction, Alert, DoctorNote, User, Ward
)

GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"

DISCLAIMER = (
    "This summary is generated by the MedNova monitoring platform from recorded device "
    "telemetry and automated risk scoring. It is decision support only -- it is not a "
    "diagnosis and does not replace assessment by a qualified clinician. Automated risk "
    "scores can be wrong in both directions. Treat the patient, not the report, and "
    "escalate on clinical judgement regardless of the risk level shown here."
)

# Next steps keyed on risk level -- these mirror the thresholds AlertService already uses.
NEXT_STEPS: Dict[str, List[str]] = {
    "critical": [
        "Attend the bedside now and perform a full clinical assessment.",
        "Confirm airway patency, circuit integrity and effective ventilation.",
        "Escalate to the responsible physician / rapid response immediately.",
        "Verify readings against a second monitor before acting on numbers alone.",
    ],
    "high": [
        "Review the patient at the bedside within the next few minutes.",
        "Check oxygenation and consider adjusting FiO2 or ventilator support.",
        "Notify the responsible physician and document the response.",
        "Re-evaluate after 15 minutes and record the outcome as follow-up.",
    ],
    "medium": [
        "Review the trend and confirm the readings are artefact-free.",
        "Increase observation frequency until the trend stabilises.",
        "Record a clinician note describing what was checked.",
    ],
    "low": [
        "Continue routine monitoring at the existing interval.",
        "Record a follow-up note if anything was actioned.",
    ],
    "normal": [
        "Continue routine monitoring; no immediate action indicated.",
        "Reassess if the patient's condition or ventilator settings change.",
    ],
}


_SEVERITY_ORDER = ["normal", "low", "medium", "high", "critical"]


def _fmt(value: Optional[datetime]) -> str:
    return value.strftime("%Y-%m-%d %H:%M UTC") if value else "not recorded"


def effective_risk_level(ctx: Dict[str, Any]) -> str:
    """
    Next steps key off the WORSE of the model's risk level and any unresolved alert.

    The score reflects the most recent reading only, so a record can read 'low' while a
    critical alert from minutes ago is still open. Telling a nurse to "continue routine
    monitoring" in that state is the one failure mode this report must not have.
    """
    pred = ctx.get("prediction")
    level = pred.risk_level if pred is not None else "normal"
    worst = max(
        (a.alert_type for a in ctx.get("open_alerts", []) if a.alert_type in _SEVERITY_ORDER),
        key=_SEVERITY_ORDER.index,
        default="normal",
    )
    return max(level, worst, key=lambda x: _SEVERITY_ORDER.index(x) if x in _SEVERITY_ORDER else 0)


async def build_report_context(db: AsyncSession, patient: Patient) -> Dict[str, Any]:
    """Collects every clinical fact the report needs, in one place."""
    latest_reading = (await db.execute(
        select(SensorReading)
        .where(SensorReading.patient_id == patient.patient_id)
        .order_by(desc(SensorReading.timestamp)).limit(1)
    )).scalars().first()

    # A short trend gives the narrative something to reason about beyond one snapshot.
    recent_readings = list((await db.execute(
        select(SensorReading)
        .where(SensorReading.patient_id == patient.patient_id)
        .order_by(desc(SensorReading.timestamp)).limit(10)
    )).scalars().all())

    prediction = (await db.execute(
        select(AIPrediction)
        .where(AIPrediction.patient_id == patient.patient_id)
        .order_by(desc(AIPrediction.created_at)).limit(1)
    )).scalars().first()

    open_alerts = list((await db.execute(
        select(Alert)
        .where(Alert.patient_id == patient.patient_id, Alert.status != "resolved")
        .order_by(desc(Alert.created_at)).limit(10)
    )).scalars().all())

    notes = list((await db.execute(
        select(DoctorNote)
        .where(DoctorNote.patient_id == patient.patient_id)
        .order_by(desc(DoctorNote.created_at)).limit(5)
    )).scalars().all())

    ward = None
    if patient.ward_id:
        ward = (await db.execute(
            select(Ward).where(Ward.ward_id == patient.ward_id)
        )).scalars().first()

    follow_up_author = None
    if prediction is not None and prediction.follow_up_by:
        follow_up_author = (await db.execute(
            select(User).where(User.user_id == prediction.follow_up_by)
        )).scalars().first()

    return {
        "patient": patient,
        "ward": ward,
        "latest_reading": latest_reading,
        "recent_readings": recent_readings,
        "prediction": prediction,
        "open_alerts": open_alerts,
        "notes": notes,
        "follow_up_author": follow_up_author,
    }


def _observations(ctx: Dict[str, Any]) -> List[str]:
    """
    Derives presenting signs from telemetry. The schema has no free-text symptom field,
    so 'symptoms' here means the objective signs the device actually recorded.
    """
    reading = ctx["latest_reading"]
    if reading is None:
        return []

    spo2, hr, temp = float(reading.spo2), float(reading.heart_rate), float(reading.temperature)
    signs = []
    if spo2 < 90:
        signs.append(f"Hypoxaemia -- SpO2 {spo2:.0f}% (below 90%)")
    elif spo2 < 95:
        signs.append(f"Borderline oxygenation -- SpO2 {spo2:.0f}%")
    else:
        signs.append(f"Oxygenation within range -- SpO2 {spo2:.0f}%")

    if hr > 120:
        signs.append(f"Tachycardia -- heart rate {hr:.0f} bpm")
    elif hr < 50:
        signs.append(f"Bradycardia -- heart rate {hr:.0f} bpm")
    else:
        signs.append(f"Heart rate within range -- {hr:.0f} bpm")

    if temp >= 38.0:
        signs.append(f"Pyrexia -- temperature {temp:.1f} C")
    elif temp < 35.0:
        signs.append(f"Hypothermia -- temperature {temp:.1f} C")
    else:
        signs.append(f"Temperature within range -- {temp:.1f} C")
    return signs


def _facts_block(ctx: Dict[str, Any]) -> str:
    """The exact facts handed to Gemini. Nothing else is sent."""
    p, r, pred = ctx["patient"], ctx["latest_reading"], ctx["prediction"]
    lines = [
        f"Age: {p.age}; Sex: {p.gender}; Ventilator status: {p.ventilator_status}",
        f"Observations: {'; '.join(_observations(ctx)) or 'no telemetry recorded'}",
    ]
    if r is not None:
        lines.append(f"Reading taken: {_fmt(r.timestamp)}")
    if pred is not None:
        lines.append(f"Automated risk level: {pred.risk_level} ({pred.risk_score}/100)")
        lines.append(f"System recommendation: {pred.recommendation or 'none recorded'}")
        lines.append(f"Clinician follow-up: {pred.follow_up_status}"
                     + (f" -- note: {pred.clinician_note}" if pred.clinician_note else ""))
    else:
        lines.append("Automated risk level: no prediction on record")
    if ctx["open_alerts"]:
        lines.append("Open alerts: " + "; ".join(
            f"{a.alert_type}: {a.message}" for a in ctx["open_alerts"][:5]))
    if len(ctx["recent_readings"]) > 1:
        trend = ", ".join(f"{float(x.spo2):.0f}%" for x in reversed(ctx["recent_readings"]))
        lines.append(f"Recent SpO2 trend (oldest to newest): {trend}")
    return "\n".join(lines)


async def _narrative_via_gemini(facts: str) -> Optional[str]:
    """
    Asks Gemini for the prose paragraph only. Returns None on any failure so the caller
    falls back -- a report that cannot be produced is worse than one without prose.
    """
    if not settings.GEMINI_API_KEY:
        return None

    prompt = (
        "You are assisting a clinician reviewing an ICU ventilator monitoring record. "
        "Using ONLY the facts below, write a 3-4 sentence clinical summary in plain "
        "professional English. Do not invent findings, vitals, diagnoses, drugs or "
        "history that are not listed. Do not give a definitive diagnosis. Do not use "
        "bullet points or headings. If the data is sparse, say so plainly.\n\n"
        f"FACTS:\n{facts}"
    )
    try:
        async with httpx.AsyncClient(timeout=settings.GEMINI_TIMEOUT_SECONDS) as client:
            resp = await client.post(
                GEMINI_URL.format(model=settings.GEMINI_MODEL),
                params={"key": settings.GEMINI_API_KEY},
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    # Low temperature: this is a clinical document, not creative writing.
                    "generationConfig": {"temperature": 0.2, "maxOutputTokens": 400},
                },
            )
        if resp.status_code != 200:
            logger.warn("Gemini summary failed", status_code=resp.status_code, body=resp.text[:200])
            return None
        parts = resp.json()["candidates"][0]["content"]["parts"]
        text = "".join(p.get("text", "") for p in parts).strip()
        return text or None
    except Exception as e:
        logger.warn("Gemini summary unavailable, using rule-based narrative", error=str(e))
        return None


def _narrative_fallback(ctx: Dict[str, Any]) -> str:
    """Deterministic prose so a missing/failing API key never blocks a report."""
    p, pred = ctx["patient"], ctx["prediction"]
    signs = _observations(ctx)
    parts = [
        f"{p.name} is a {p.age}-year-old {p.gender} patient with ventilator status "
        f"'{p.ventilator_status}'."
    ]
    parts.append("Latest recorded observations: " + "; ".join(signs).lower() + "."
                 if signs else "No device telemetry has been recorded for this patient yet.")
    if pred is not None:
        parts.append(
            f"Automated scoring places the patient at {pred.risk_level} risk "
            f"({pred.risk_score}/100), and clinician follow-up is currently "
            f"'{pred.follow_up_status}'."
        )
    else:
        parts.append("No automated risk prediction is on record for this patient.")
    if ctx["open_alerts"]:
        parts.append(f"There are {len(ctx['open_alerts'])} unresolved alert(s) on this record.")
    return " ".join(parts)


def render_markdown(ctx: Dict[str, Any], narrative: str, source: str) -> str:
    """Assembles the downloadable document."""
    p, pred, r = ctx["patient"], ctx["prediction"], ctx["latest_reading"]
    ward = ctx["ward"]
    risk_level = effective_risk_level(ctx)
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    out: List[str] = [
        f"# Patient Summary -- {p.name}",
        "",
        f"**Generated:** {generated}  ",
        f"**Bed:** {p.bed_number or 'N/A'}  ",
        f"**Ward:** {ward.name if ward else 'Unassigned'}  ",
        f"**Age / Sex:** {p.age} / {p.gender}  ",
        f"**Ventilator status:** {p.ventilator_status}  ",
        f"**Narrative source:** {source}",
        "",
        "## Clinical Summary",
        "",
        narrative,
        "",
        "## Presenting Signs & Observations",
        "",
    ]

    signs = _observations(ctx)
    if signs:
        out += [f"- {s}" for s in signs]
        out += ["", f"*Recorded {_fmt(r.timestamp) if r else 'not recorded'}.*"]
    else:
        out.append("- No device telemetry has been recorded for this patient.")

    out += ["", "## Risk Assessment", ""]
    if pred is not None:
        out += [
            f"- **Risk level:** {pred.risk_level.upper()} ({pred.risk_score}/100)",
            f"- **Model confidence:** {round(float(pred.confidence) * 100)}%",
            f"- **Model version:** {pred.model_version}",
            f"- **Assessed:** {_fmt(pred.created_at)}",
            "",
            "### System Recommendation",
            "",
            pred.recommendation or "_No recommendation recorded._",
            "",
            "### Clinician Follow-up",
            "",
            f"- **Status:** {pred.follow_up_status}",
            f"- **Note:** {pred.clinician_note or '_none recorded_'}",
            f"- **Updated by:** {ctx['follow_up_author'].name if ctx['follow_up_author'] else 'not yet actioned'}"
            + (f" on {_fmt(pred.follow_up_at)}" if pred.follow_up_at else ""),
        ]
    else:
        out.append("_No automated risk prediction is on record for this patient._")

    out += ["", "## Open Alerts", ""]
    if ctx["open_alerts"]:
        out += [f"- **{a.alert_type.upper()}** ({a.status}) -- {a.message} _({_fmt(a.created_at)})_"
                for a in ctx["open_alerts"]]
    else:
        out.append("- None. No unresolved alerts on this record.")

    if ctx["notes"]:
        out += ["", "## Recent Clinician Notes", ""]
        out += [f"- _{_fmt(n.created_at)}_ -- {n.note_text}" for n in ctx["notes"]]

    out += ["", "## Recommended Next Steps", ""]
    model_level = pred.risk_level if pred is not None else "normal"
    if risk_level != model_level:
        out += [
            f"> **Escalated from '{model_level}' to '{risk_level}'** because an unresolved "
            f"{risk_level} alert is open on this record. Act on the higher level.",
            "",
        ]
    out += [f"{i}. {step}" for i, step in enumerate(NEXT_STEPS.get(risk_level, NEXT_STEPS["normal"]), 1)]

    out += [
        "",
        "---",
        "",
        "## Medical Disclaimer",
        "",
        DISCLAIMER,
        "",
        f"_MedNova Health Systems -- generated {generated} for internal clinical use._",
        "",
    ]
    return "\n".join(out)


async def generate_patient_report(db: AsyncSession, patient: Patient) -> Dict[str, Any]:
    """Builds the full report. Never raises for a missing Gemini key."""
    ctx = await build_report_context(db, patient)
    facts = _facts_block(ctx)

    narrative = await _narrative_via_gemini(facts)
    source = f"Gemini ({settings.GEMINI_MODEL})" if narrative else "Rule-based (Gemini unavailable)"
    if not narrative:
        narrative = _narrative_fallback(ctx)

    pred = ctx["prediction"]
    escalated = effective_risk_level(ctx)
    return {
        "patient_id": str(patient.patient_id),
        "patient_name": patient.name,
        "generated_at": datetime.utcnow(),
        "narrative_source": source,
        "risk_level": pred.risk_level if pred is not None else None,
        "risk_score": pred.risk_score if pred is not None else None,
        "summary": narrative,
        "next_steps": NEXT_STEPS.get(escalated, NEXT_STEPS["normal"]),
        "disclaimer": DISCLAIMER,
        "markdown": render_markdown(ctx, narrative, source),
    }
